name: Godot CI
on:
  push:
    tags:
      - 'v*'

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Wine
        id: wine_install
        run: |
          sudo apt install wine64
          wine64 --version
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_export_templates.tpz
          relative_project_path: ./
          cache: true
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      - name: Rename archives
        id: archive_name
        run: |
          cd ${{ steps.export.outputs.archive_directory }}
          mv "Windows Desktop.zip" "${{ github.event.repository.name }}.${{ github.ref_name }}.windows.zip"
          mv "macOS.zip" "${{ github.event.repository.name }}.${{ github.ref_name }}.mac.zip"
          mv "LinuxX11.zip" "${{ github.event.repository.name }}.${{ github.ref_name }}.linux.zip"
          mv "Web.zip" "${{ github.event.repository.name }}.${{ github.ref_name }}.web.zip"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          7z x butler.zip
          sudo cp butler /usr/bin
          sudo chmod +x /usr/bin/butler
          butler -V
      - name: Butler upload
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_GAME: ${{ github.event.repository.name }}
          ITCH_USER: brawmario
          VERSION: ${{ github.ref_name }}
          WINDOWS_ARCHIVE: ${{ steps.export.outputs.archive_directory }}/${{ github.event.repository.name }}.${{ github.ref_name }}.windows.zip
          MACOS_ARCHIVE: ${{ steps.export.outputs.archive_directory }}/${{ github.event.repository.name }}.${{ github.ref_name }}.mac.zip
          LINUX_ARCHIVE: ${{ steps.export.outputs.archive_directory }}/${{ github.event.repository.name }}.${{ github.ref_name }}.linux.zip
          WEB_ARCHIVE: ${{ steps.export.outputs.archive_directory }}/${{ github.event.repository.name }}.${{ github.ref_name }}.web.zip
        run: |
          butler push "${{ env.WINDOWS_ARCHIVE }}" ${{ env.ITCH_USER }}/${{ env.ITCH_GAME }}:windows --userversion ${{ env.VERSION }}
          butler push "${{ env.MACOS_ARCHIVE }}"   ${{ env.ITCH_USER }}/${{ env.ITCH_GAME }}:mac     --userversion ${{ env.VERSION }}
          butler push "${{ env.LINUX_ARCHIVE }}"   ${{ env.ITCH_USER }}/${{ env.ITCH_GAME }}:linux   --userversion ${{ env.VERSION }}
          butler push "${{ env.WEB_ARCHIVE }}"     ${{ env.ITCH_USER }}/${{ env.ITCH_GAME }}:web     --userversion ${{ env.VERSION }}
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ steps.export.outputs.build_directory }}/Web
