name: godot-ci export
on:
  push:
#    tags:
#      - 'v*'

env:
  GODOT_VERSION: 4.0

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Export
        id: export
        uses: firebelley/godot-export@v4.7.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          use_preset_export_path: true
          use_godot_4: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-wordle.${{ github.ref_name }}.${{ matrix.PLATFORM }}
          path: ${{ steps.export.outputs.archive_directory }}/*
#      - name: Butler Upload
#        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
#        env:
#          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
#          CHANNEL: ${{ matrix.PLATFORM }}
#          ITCH_GAME: godot-wordle
#          ITCH_USER: brawmario
#          PACKAGE: build/${{ matrix.PLATFORM }}
#          VERSION: ${{ github.ref_name }}
#      - name: Install rsync
#        if: matrix.PLATFORM == 'web'
#        run: |
#          apt-get update && apt-get install -y rsync
#      - name: Deploy to GitHub Pages
#        if: matrix.PLATFORM == 'web'
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: build/web